### ISSUE TITLE
Cannot Build Project

### ISSUE THREAD

**Issue by rorymurphyza** [matthid/s2client-dotnet#1]
Hi there,
Firstly, thanks for this awesome package, I am really happy to have something like this to play around in. I am excited to start using it, but I am struggling with the paket dependency as I have never used it before.
When I load the s2client-proto.csproj into VS2017, I am not able to build it as I am getting this:

> Error	MSB3073	The command ""C:\Coding\Starcraft 2\s2client-dotnet\.paket\paket.exe" restore" exited with code 9009.	s2client-proto	C:\Coding\Starcraft 2\s2client-dotnet\.paket\Paket.Restore.targets	50	

Looking at the file references here, I see it calls PaketCommand, which I haven't seen before. I tried downloading Paket from NuGet into my solution, but I am still getting the error.

Is there any way you could help me out on getting this project built? It would be much appreciated

**Comment by matthid** [comment]
It seems like the paket bootstrapper is not checked in (my fault because *.exe is ignored by default):
Will fix soon. For now please try to download the latest `paket.bootstrapper.exe` from https://github.com/fsprojects/Paket/releases/tag/5.114.5, rename it to `paket.exe` and put it into the `.paket` folder.

This should already work for you, but there are some docs missing because to build via `build.fsx` you can do the following:

1. Install FAKE via chocolatey: https://chocolatey.org/packages/fake (ie `choco install fake --pre`)
2. run `fake run build.fsx` in the command line in the project directory.

This will restore all dependencies and build the project initially.
Once build you should be able to open and build the project in visual studio as well.

**Comment by matthid** [comment]
@rorymurphyza Ok I have added some docs and noticed that there is a bit more to do, see https://github.com/matthid/s2client-dotnet#building if you have any problems with getting it to run don't hesitate to ask either here or on gitter chat (https://gitter.im/matthid/Yaaf).

**Comment by rorymurphyza** [comment]
Awesome, that makes a lot more sense now. I have been able to build the project with fake but not with 
`dotnet pack` (I get a `paket file for the framework 'netcoreapp2.0' is missing` error, I'll take a look at this later). 
I'm also getting a WebSockets exception in ProtobufConnection.fs:96, which I'll have to figure out as well.

Thanks for doing all this and your help so far. I'll let you know once I have had a bit of time to figure out these error (I've never used F# before, so I see some Googling ahead...)

**Comment by matthid** [comment]
I'm sorry that this is quite an early stage. There will be a nuget package eventually. Now that someone is interested I might speed that up a bit ;)

**Comment by rorymurphyza** [comment]
No worries. I'm quite new to this type of coding, I've spent my life writing C and C++ for big corporates. I'm very happy to help out if you have a couple of tasks you can send over to me. It's the best way to learn.

**Comment by matthid** [comment]
Ok we now have a 1 step release script and a ready to use package on nuget (https://www.nuget.org/packages/s2client-dotnet). Let me know if you still encounter issues.
